### ISSUE TITLE
KeyError: 'temps'

### ISSUE THREAD

**Issue by techied** [tapnair/OctoPiLCD#1]
I get an error when I try to manually run the python file.

Traceback (most recent call last):
File "OctoPiLCD.py", line 147, in <module>
  pData.updatePrintData()
File "OctoPiLCD.py", line 82, in updatePrintData
  self.toolTemp = printer_data['temps']['tool0']['actual]'
KeyError: 'temps'

Do you know how to fix this? It appears as if it can't get the temperature command, but I don't know python :P

**Comment by techied** [comment]
If I try to comment out said offending line (82), I get an error on the next line.

**Comment by tapnair** [comment]
Is printer_data have anything in it?

You have to change the api_key to be yours maybe you are not actually
receiving a response from the API?

**Comment by techied** [comment]
I've replaced the key variable with my api key already
for security reasons, I wont put it here :)

**Comment by Kalley82** [comment]
I had the same issue, but I added the following code between lines 79 and 80 "print printer_data" and that showed me the the JSON response does not include 'temps' but instead 'temperature'.  So replacing 'temps' in lines 80-83 fixed it.

self.toolTemp = printer_data['temperature']['tool0']['actual']
self.toolTarget = printer_data['temperature']['tool0']['target']
self.bedTemp = printer_data['temperature']['bed']['actual']
self.bedTarget = printer_data['temperature']['bed']['target']
